### ISSUE TITLE
The role of yield keyword in migen

### ISSUE THREAD

**Issue by kowalik-lukasz** [antmicro-labs/video-processing#12]
Based on the migen tutorial I already know that the "yield" keyword used on its own begins the next clock cycle. I'm not sure tho what its purpose is while referring to user-defined signals in modules. Example in the picture below. Could you please clarify this?

![image](https://user-images.githubusercontent.com/48880659/80886279-13acfb80-8cbe-11ea-9b8c-339a542fac06.png)

**Comment by tobiaszpuslecki** [comment]
https://www.geeksforgeeks.org/use-yield-keyword-instead-return-keyword-python/

**Comment by rw1nkler** [comment]
`yield`'s in migen are just for simulation purposes. Maybe some of the commonly used terms will also clarify something:
- tb is a shortcut for [test bench](https://en.wikipedia.org/wiki/Test_bench)
- dut is a shortcut for [device under test](https://en.wikipedia.org/wiki/Device_under_test)

In this situation, every time the `sevseg_tb` function will be called it will affect the `hex` signal.
In the first call, it will be equal to 0, in second - 1, etc. Using this approach we are able to "program" the behaviour of one signal in the simulation
