### ISSUE TITLE
Run Linux on Zynq

### ISSUE THREAD

**Issue by rw1nkler** [antmicro-labs/video-processing#4]
For preparing the needed binaries, use the [Enclustra Build Environment](https://github.com/enclustra-bsp/bsp-xilinx). All the information should be available in the project [documentation](http://enclustra.github.io/ebe-docs/user-doc-xilinx/index_xilinx.html).

**Comment by tobiaszpuslecki** [comment]
During configuration, after chose "Zynq-7000", what will be set later? Docs of board tell, that there are 2 configuration - Mars ZX2 and Mars ZX3. Next, I don't know base board type and other information (expect boot device. MMC == microSD?). @rw1nkler could you give me more information about it?

**Comment by kgugala** [comment]
the modules you got are `MA-ZX3-20-2I-D10`. You can boot from an SD card.

EBE docs discusses the boot medium creation in the [Deployment](https://enclustra.github.io/ebe-docs/user-doc-xilinx/index_xilinx.html#deployment) section.

**Comment by tobiaszpuslecki** [comment]
Is it correct result? @kgugala @rw1nkler 


> .[1m        __   _ __      _  __.[0m
> .[1m       / /  (_) /____ | |/_/.[0m
> .[1m      / /__/ / __/ -_)>  <.[0m
> .[1m     /____/_/\__/\__/_/|_|.[0m
> .[1m SoC BIOS / CPU: VexRiscv / 100MHz.[0m
> (c) Copyright 2012-2018 Enjoy-Digital
> (c) Copyright 2007-2018 M-Labs Limited
> Built Feb 20 2019 19:26:07
> 
> BIOS CRC passed (a8f9ba0d)
> Booting from serial...
> Press Q or ESC to abort boot completely.
> sL5DdSMmkekro
> Timeout
> Executing booted program at 0x40000000
> Zephyr Shell, Zephyr version: 1.13.0-rc1
> Type 'help' for a list of available commands
> shell> 
> Zynq Video Board test program riscv32
> Zynq Video Board initialized

**Comment by kgugala** [comment]
the output looks fine. Did you connect an HDMI display? You should get the video stream from one of the cameras.

**Comment by tobiaszpuslecki** [comment]
Yes, I did. The video stream is from right camera. 
@kgugala Could you give us  further guidance?

**Comment by kgugala** [comment]
@tobiaszpuslecki some time ago I created additional issues describing what need to be done next. Did you see them?

**Comment by tobiaszpuslecki** [comment]
@kgugala Yes, I did. I kindly thanks for it, but due to current situation, I couldn't do something more. Now, I try to understand, how exactly develop software for our boards.

**Comment by kgugala** [comment]
We can schedule a telco and discuss the tasks. When you can have it?

**Comment by tobiaszpuslecki** [comment]
Our leader will send today an email about telco
