### ISSUE TITLE
Get familiar with litex manual and build design for arty simulation

### ISSUE THREAD

**Issue by kowalik-lukasz** [antmicro-labs/video-processing#8]
Build new design for ARTY board, run design in simulation. 
Build design for zynq board with copied def arty and defined ports and interfaces.
Take names for ports and devices from vivado.

**Comment by kgugala** [comment]
please provide the description of this task

**Comment by tobiaszpuslecki** [comment]
@kgugala when I tried to build arty board (after install every listed tools), there is a problem with riscv tools. I don't understand why commands are unable to find, since I build riscv toolchain. Is it a problem with environmental path?





Traceback (most recent call last):
  File "./arty.py", line 115, in <module>
    main()
  File "./arty.py", line 111, in main
    builder.build(**vivado_build_argdict(args))
  File "/home/tobi/Desktop/litex/litex/soc/integration/builder.py", line 201, in build
    self._generate_includes()
  File "/home/tobi/Desktop/litex/litex/soc/integration/builder.py", line 90, in _generate_includes
    for k, v in export.get_cpu_mak(self.soc.cpu, self.compile_software):
  File "/home/tobi/Desktop/litex/litex/soc/integration/export.py", line 85, in get_cpu_mak
    ("TRIPLE", select_triple(triple)),
  File "/home/tobi/Desktop/litex/litex/soc/integration/export.py", line 80, in select_triple
    raise OSError(msg)
OSError: Unable to find any of the cross compilation toolchains:
- riscv64-unknown-elf
- riscv32-unknown-elf
- riscv-none-embed
- riscv64-linux
- riscv-sifive-elf
- riscv64-none-elf

**Comment by kgugala** [comment]
This means that you don't have RISC-V toolchain binary in your PATH. Can you point to the guide you're using?

**Comment by tobiaszpuslecki** [comment]
I’m only using this guide -> https://github.com/antmicro-labs/video-processing/wiki/LiteX---Zephyr-tutorial

I’m not sure, what exactly will should be in PATH, if we talk about RISC-V toolchain. Could you tell me, what do you have in your PATH? (Refer to RISC-V)

**Comment by rw1nkler** [comment]
You have to add the following line to your `~/.bashrc`:
```
export PATH="$PATH:/opt/riscv/bin"
```

**Comment by tobiaszpuslecki** [comment]
It works. But there is another problem. After I tried to run ./arty.py, there is error shown below.

make: Leaving directory '/home/tobi/Desktop/litex/litex/boards/targets/soc_basesoc_arty/software/bios'
application-specific initialization failed: couldn't load file "librdi_commontasks.so": libtinfo.so.5: cannot open shared object file: No such file or directory

(...)


top.v file is generated, but top.bit not. I cannot to find librdi_commontasks.so anywhere. Could you  tell me why?

**Comment by rw1nkler** [comment]
Maybe this will help:
https://forums.xilinx.com/t5/Installation-and-Licensing/Installing-Vivado-2018-1-on-Fedora-28/td-p/855996

**Comment by kowalik-lukasz** [comment]
> @kgugala when I tried to build arty board (after install every listed tools), there is a problem with riscv tools. I don't understand why commands are unable to find, since I build riscv toolchain. Is it a problem with environmental path?
> 
> Traceback (most recent call last):
> File "./arty.py", line 115, in
> main()
> File "./arty.py", line 111, in main
> builder.build(**vivado_build_argdict(args))
> File "/home/tobi/Desktop/litex/litex/soc/integration/builder.py", line 201, in build
> self._generate_includes()
> File "/home/tobi/Desktop/litex/litex/soc/integration/builder.py", line 90, in _generate_includes
> for k, v in export.get_cpu_mak(self.soc.cpu, self.compile_software):
> File "/home/tobi/Desktop/litex/litex/soc/integration/export.py", line 85, in get_cpu_mak
> ("TRIPLE", select_triple(triple)),
> File "/home/tobi/Desktop/litex/litex/soc/integration/export.py", line 80, in select_triple
> raise OSError(msg)
> OSError: Unable to find any of the cross compilation toolchains:
> 
>     * riscv64-unknown-elf
> 
>     * riscv32-unknown-elf
> 
>     * riscv-none-embed
> 
>     * riscv64-linux
> 
>     * riscv-sifive-elf
> 
>     * riscv64-none-elf

I have the same problem but in my case adding PATH to bashrc didn't change anything.

**Comment by rw1nkler** [comment]
Where did you install the toolchain? You have to add path to the toolchain bin directory to your PATH variable.

**Comment by kowalik-lukasz** [comment]
@rw1nkler It's in the same directory as mentioned above - /opt/riscv/bin.

**Comment by rw1nkler** [comment]
Please, paste here the result of the following commands:
```
which riscv64-unknown-elf-gcc
stat /opt/riscv/bin
stat /opt/riscv/bin/riscv64-unknown-elf-gcc
echo $PATH
```

**Comment by kowalik-lukasz** [comment]
`exweap@exweap-Lenovo-Y520-15IKBN:~$ which riscv64-unknown-elf-gcc
/opt/riscv/bin/riscv64-unknown-elf-gcc
exweap@exweap-Lenovo-Y520-15IKBN:~$ stat /opt/riscv/bin
  File: /opt/riscv/bin
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 806h/2054d	Inode: 20840531    Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-15 00:11:06.263564729 +0200
Modify: 2020-05-15 00:09:27.379517771 +0200
Change: 2020-05-15 00:09:27.379517771 +0200
 Birth: -
exweap@exweap-Lenovo-Y520-15IKBN:~$ stat /opt/riscv/bin/riscv64-unknown-elf-gcc
  File: /opt/riscv/bin/riscv64-unknown-elf-gcc
  Size: 6196120   	Blocks: 12104      IO Block: 4096   regular file
Device: 806h/2054d	Inode: 20841665    Links: 2
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-15 00:11:06.267564730 +0200
Modify: 2020-05-15 00:09:27.031517601 +0200
Change: 2020-05-15 00:09:27.039517605 +0200
 Birth: -
exweap@exweap-Lenovo-Y520-15IKBN:~$ echo $PATH
/tools/Xilinx/DocNav:/tools/Xilinx/Vivado/2019.2/bin:/home/exweap/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/riscv/bin:/opt/riscv/bin
`

**Comment by kowalik-lukasz** [comment]
```
exweap@exweap-Lenovo-Y520-15IKBN:~$ which riscv64-unknown-elf-gcc
/opt/riscv/bin/riscv64-unknown-elf-gcc
exweap@exweap-Lenovo-Y520-15IKBN:~$ stat /opt/riscv/bin
  File: /opt/riscv/bin
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 806h/2054d	Inode: 20840531    Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-15 00:11:06.263564729 +0200
Modify: 2020-05-15 00:09:27.379517771 +0200
Change: 2020-05-15 00:09:27.379517771 +0200
 Birth: -
exweap@exweap-Lenovo-Y520-15IKBN:~$ stat /opt/riscv/bin/riscv64-unknown-elf-gcc
  File: /opt/riscv/bin/riscv64-unknown-elf-gcc
  Size: 6196120   	Blocks: 12104      IO Block: 4096   regular file
Device: 806h/2054d	Inode: 20841665    Links: 2
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-15 00:11:06.267564730 +0200
Modify: 2020-05-15 00:09:27.031517601 +0200
Change: 2020-05-15 00:09:27.039517605 +0200
 Birth: -
exweap@exweap-Lenovo-Y520-15IKBN:~$ echo $PATH
/tools/Xilinx/DocNav:/tools/Xilinx/Vivado/2019.2/bin:/home/exweap/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/riscv/bin:/opt/riscv/bin
```

**Comment by rw1nkler** [comment]
The toolchain is both in your filesystem and in your path. That is a strange situation. Can you post here the whole log from running `arty.py` file?

Please, attach it as a separate file with `.log` extension

**Comment by kowalik-lukasz** [comment]
[arty.log](https://github.com/antmicro-labs/video-processing/files/4646774/arty.log)

**Comment by kowalik-lukasz** [comment]
@rw1nkler So does the .log file say anything useful?
